services:
  mailpit:
    image: axllent/mailpit:v1.20
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    environment:
      TZ: ${TIME_ZONE}
