services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
    container_name: sqlserver
    user: root
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Developer
      MSSQL_LCID: 1041 # https://www.ryadel.com/en/microsoft-windows-lcid-list-decimal-and-hex-all-locale-codes-ids/
      MSSQL_COLLATION: Japanese_CI_AS
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: db-data
        target: /var/opt/mssql/data
      - type: volume
        source: db-log
        target: /var/opt/mssql/log
      - type: volume
        source: db-secrets
        target: /var/opt/mssql/sec
volumes:
  db-data:
  db-log:
  db-secrets:
