services:
  redis:
    image: redis/redis-stack:7.4.0-v2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - type: volume
        source: redis-data
        target: /data
volumes:
  redis-data:
