name: 'postgres'

services:
  db:
    image: postgres:17.5-bookworm
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    ports:
      - "5432:5432"
  ui:
    image: dpage/pgadmin4:9.5
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # servers.json で使用する環境変数をpgAdminコンテナに渡す
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      # pgAdmin に servers.json の場所を教える
      PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers/servers.json
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json.template:/pgadmin4/servers.json.template
      - ./pgadmin_entrypoint.sh:/pgadmin_entrypoint.sh
    entrypoint: [ "/bin/bash", "/pgadmin_entrypoint.sh" ]
    depends_on:
      - db
volumes:
  db-data:
  pgadmin-data:


